# Parámetros juego
ANCHO_PANTALLA = 640
ALTO_PANTALLA  = 480
VELOCIDAD = 5
TAMANNO_BLOQUE = 80 # Sirve bien con 20, 40, 80

# Parámetros algoritmo genetico
CANTIDAD_AGENTES = 30
CANTIDAD_GENERACIONES = 50

TASA_MUTACION = 0.1